# Generated by Django 4.2.1 on 2023-06-06 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubCategoria',
            new_name='SubCategory',
        ),
    ]
